### PR TITLE
Try to play with fasthttp

### PR DESCRIPTION
**Pull request by ciricode**

### CODE REVIEW

**Comment by ging-dev** [comment]
Does it reduce performance significantly?

**Comment by ciricode** [comment]
> Does it reduce performance significantly?

Do you want me to add benchmarks to them?

**Comment by ging-dev** [comment]
> > Does it reduce performance significantly?
> 
> Do you want me to add benchmarks to them?

yep

**Comment by ciricode** [comment]
> > > Does it reduce performance significantly?
> > 
> > 
> > Do you want me to add benchmarks to them?
> 
> yep


`fasthttp.RequestHeader` is 20% slower than normal printing.

**Pull request closed without merging**
